sudo: false

language: cpp

before_script:
  - git clone https://github.com/schrodinger/maeparser.git
  - mkdir maeparser/build
  - cd maeparser/build
  - cmake ..
  - make install

script:
  - mkdir build
  - cd build
  - export CXX="g++-4.8"
  - cmake ..
  - make
  - make test CTEST_OUTPUT_ON_FAILURE=1

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-4.8
      - g++-4.8
      - libboost-all-dev

